// Release builds rewrite bundled Rolldown's native binding requires from
// `@rolldown/binding-<platform>` to the Vite+ platform packages
// (`<packageName>-<platform>`), whose merged `.node` contains
// `rolldown_binding`. Core declares those packages as `optionalDependencies`
// at publish time (see packages/cli/publish-native-addons.ts), so the bundled
// loader resolves through declared dependencies instead of requiring back into
// `vite-plus`. See rfcs/core-binding-resolution.md.
//
// This is a text transform rather than a `rewriteModuleSpecifiers` rule
// because the version-guard rewrite is not a module specifier and must stay
// paired with its branch's specifier rewrite, so one module owns both and the
// caller can assert the pairing.

export interface RewriteRolldownBindingOptions {
  /** The napi `packageName` platform packages derive from, e.g. `@voidzero-dev/vite-plus`. */
  packageName: string;
  /**
   * napi platform suffixes Vite+ ships native packages for, e.g.
   * `darwin-arm64`, `linux-x64-musl` (derived from the CLI's `napi.targets`).
   * Specifiers for other platforms, including the `wasm32-wasi` fallback,
   * are left on `@rolldown/binding-*` and keep their upstream version guards.
   */
  platformSuffixes: ReadonlySet<string>;
  /** Version the platform packages are published as (core's own version). */
  version: string;
}

export interface RewriteRolldownBindingResult {
  source: string;
  /** Platform suffixes whose loader branch was redirected. */
  rewrittenSuffixes: Set<string>;
  /** `@rolldown/binding-<suffix>` occurrences rewritten (two per branch). */
  specifierRewrites: number;
  /** Version guards rewritten (one per branch). */
  guardRewrites: number;
}

const SPECIFIER_RE = /@rolldown\/binding-([a-z0-9-]+)/g;

// A rewritten platform branch's version guard, generated by napi-rs:
//
//   const bindingPackageVersion = __require("<packageName>-<suffix>/package.json").version;
//   if (bindingPackageVersion !== "<rolldown version>" && ...) throw new Error(`... expected <rolldown version> but got ...`);
//
// Anchoring on the rewritten specifier scopes the version replacement to
// branches this build actually redirects; guards of platforms left on
// `@rolldown/binding-*` keep comparing against the Rolldown version. Matching
// bare `require(` also covers the bundled chunks' `__require(` calls.
function buildGuardRe(packageName: string): RegExp {
  const escaped = packageName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(
    `(require\\(["']${escaped}-[a-z0-9-]+\\/package\\.json["']\\)\\.version;\\s*if \\(bindingPackageVersion !== )(["'])[^"']+\\2([\\s\\S]{0,400}?expected )\\S+( but got)`,
    'g',
  );
}

export function rewriteRolldownBindingRequires(
  source: string,
  { packageName, platformSuffixes, version }: RewriteRolldownBindingOptions,
): RewriteRolldownBindingResult {
  const rewrittenSuffixes = new Set<string>();
  let specifierRewrites = 0;
  let rewritten = source.replace(SPECIFIER_RE, (specifier, suffix: string) => {
    if (!platformSuffixes.has(suffix)) {
      return specifier;
    }
    rewrittenSuffixes.add(suffix);
    specifierRewrites += 1;
    return `${packageName}-${suffix}`;
  });

  let guardRewrites = 0;
  rewritten = rewritten.replace(
    buildGuardRe(packageName),
    (_match, head: string, quote: string, mid: string, tail: string) => {
      guardRewrites += 1;
      return `${head}${quote}${version}${quote}${mid}${version}${tail}`;
    },
  );

  return { source: rewritten, rewrittenSuffixes, specifierRewrites, guardRewrites };
}
