too-many-lines-threshold = 200

# We don't have any downstream users, we don't care about external API changes,
# and this makes the codebase cleaner
avoid-breaking-exported-api = false

disallowed-methods = [
  { path = "str::to_ascii_lowercase", reason = "To avoid memory allocation, use `cow_utils::CowUtils::cow_to_ascii_lowercase` instead." },
  { path = "str::to_ascii_uppercase", reason = "To avoid memory allocation, use `cow_utils::CowUtils::cow_to_ascii_uppercase` instead." },
  { path = "str::to_lowercase", reason = "To avoid memory allocation, use `cow_utils::CowUtils::cow_to_lowercase` instead." },
  { path = "str::to_uppercase", reason = "To avoid memory allocation, use `cow_utils::CowUtils::cow_to_uppercase` instead." },
  { path = "str::replace", reason = "To avoid memory allocation, use `cow_utils::CowUtils::cow_replace` instead." },
  { path = "str::replacen", reason = "To avoid memory allocation, use `cow_utils::CowUtils::cow_replacen` instead." },
  { path = "std::env::current_dir", reason = "To get an `AbsolutePathBuf`, Use `vite_path::current_dir` instead." },
]

disallowed-types = [
  { path = "std::collections::HashMap", reason = "Use `rustc_hash::FxHashMap` instead, which is typically faster." },
  { path = "std::collections::HashSet", reason = "Use `rustc_hash::FxHashSet` instead, which is typically faster." },
  { path = "std::path::Path", reason = "Use `vite_path::RelativePath` or `vite_path::AbsolutePath` instead" },
  { path = "std::path::PathBuf", reason = "Use `vite_path::RelativePathBuf` or `vite_path::AbsolutePathBuf` instead" },
  { path = "std::string::String", reason = "Use `vite_str::Str` for small strings. For large strings, prefer `Box/Rc/Arc<str>` if mutation is not needed." },
]

disallowed-macros = [
  { path = "std::format", reason = "Use `vite_str::format` for small strings." },
  { path = "std::println", reason = "Use `vite_shared::output` functions (`info`, `note`, `success`) instead." },
  { path = "std::print", reason = "Use `vite_shared::output` functions (`info`, `note`, `success`) instead." },
  { path = "std::eprintln", reason = "Use `vite_shared::output` functions (`warn`, `error`) instead." },
  { path = "std::eprint", reason = "Use `vite_shared::output` functions (`warn`, `error`) instead." },
]

### await-holding-invalid-types
## we can remove these if https://github.com/xacrimon/dashmap/issues/348 lands

[[await-holding-invalid-types]]
path = "dashmap::mapref::one::Ref"
reason = "holding dashmap references will cause deadlocks, if the same thread tries to acquire a reference"

[[await-holding-invalid-types]]
path = "dashmap::mapref::one::RefMut"
reason = "holding dashmap references will cause deadlocks, if the same thread tries to acquire a reference"

[[await-holding-invalid-types]]
path = "dashmap::mapref::one::MappedRef"
reason = "holding dashmap references will cause deadlocks, if the same thread tries to acquire a reference"

[[await-holding-invalid-types]]
path = "dashmap::mapref::entry::Entry"
reason = "holding dashmap references will cause deadlocks, if the same thread tries to acquire a reference"

[[await-holding-invalid-types]]
path = "dashmap::mapref::multiple::RefMulti"
reason = "holding dashmap references will cause deadlocks, if the same thread tries to acquire a reference"

[[await-holding-invalid-types]]
path = "dashmap::mapref::multiple::RefMutMulti"
reason = "holding dashmap references will cause deadlocks, if the same thread tries to acquire a reference"

[[await-holding-invalid-types]]
path = "dashmap::iter::Iter"
reason = "holding dashmap references will cause deadlocks, if the same thread tries to acquire a reference"

[[await-holding-invalid-types]]
path = "dashmap::iter::IterMut"
reason = "holding dashmap references will cause deadlocks, if the same thread tries to acquire a reference"

[[await-holding-invalid-types]]
path = "dashmap::iter::OwningIter"
reason = "holding dashmap references will cause deadlocks, if the same thread tries to acquire a reference"
