catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
catalogs:
  test:
    vitest: ^4.0.0
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
