// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null;
const loadErrors = [];

const isMusl = () => {
  let musl = false;
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem();
    if (musl === null) {
      musl = isMuslFromReport();
    }
    if (musl === null) {
      musl = isMuslFromChildProcess();
    }
  }
  return musl;
};

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-');

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl');
  } catch {
    return null;
  }
};

const isMuslFromReport = () => {
  let report = null;
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true;
    report = process.report.getReport();
  }
  if (!report) {
    return null;
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false;
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true;
    }
  }
  return false;
};

const isMuslFromChildProcess = () => {
  try {
    return require('child_process')
      .execSync('ldd --version', { encoding: 'utf8' })
      .includes('musl');
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false;
  }
};

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err);
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./vite-plus.android-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-android-arm64');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-android-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./vite-plus.android-arm-eabi.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-android-arm-eabi');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-android-arm-eabi/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`));
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (
        process.config?.variables?.shlib_suffix === 'dll.a' ||
        process.config?.variables?.node_target_type === 'shared_library'
      ) {
        try {
          return require('./vite-plus.win32-x64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@voidzero-dev/vite-plus-win32-x64-gnu');
          const bindingPackageVersion =
            require('@voidzero-dev/vite-plus-win32-x64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.1.24' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./vite-plus.win32-x64-msvc.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@voidzero-dev/vite-plus-win32-x64-msvc');
          const bindingPackageVersion =
            require('@voidzero-dev/vite-plus-win32-x64-msvc/package.json').version;
          if (
            bindingPackageVersion !== '0.1.24' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./vite-plus.win32-ia32-msvc.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-win32-ia32-msvc');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-win32-ia32-msvc/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./vite-plus.win32-arm64-msvc.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-win32-arm64-msvc');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-win32-arm64-msvc/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`));
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./vite-plus.darwin-universal.node');
    } catch (e) {
      loadErrors.push(e);
    }
    try {
      const binding = require('@voidzero-dev/vite-plus-darwin-universal');
      const bindingPackageVersion =
        require('@voidzero-dev/vite-plus-darwin-universal/package.json').version;
      if (
        bindingPackageVersion !== '0.1.24' &&
        process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
        process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
      ) {
        throw new Error(
          `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
        );
      }
      return binding;
    } catch (e) {
      loadErrors.push(e);
    }
    if (process.arch === 'x64') {
      try {
        return require('./vite-plus.darwin-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-darwin-x64');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-darwin-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./vite-plus.darwin-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-darwin-arm64');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-darwin-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`));
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./vite-plus.freebsd-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-freebsd-x64');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-freebsd-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./vite-plus.freebsd-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-freebsd-arm64');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-freebsd-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`));
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./vite-plus.linux-x64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@voidzero-dev/vite-plus-linux-x64-musl');
          const bindingPackageVersion =
            require('@voidzero-dev/vite-plus-linux-x64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.1.24' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./vite-plus.linux-x64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@voidzero-dev/vite-plus-linux-x64-gnu');
          const bindingPackageVersion =
            require('@voidzero-dev/vite-plus-linux-x64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.1.24' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./vite-plus.linux-arm64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@voidzero-dev/vite-plus-linux-arm64-musl');
          const bindingPackageVersion =
            require('@voidzero-dev/vite-plus-linux-arm64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.1.24' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./vite-plus.linux-arm64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@voidzero-dev/vite-plus-linux-arm64-gnu');
          const bindingPackageVersion =
            require('@voidzero-dev/vite-plus-linux-arm64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.1.24' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./vite-plus.linux-arm-musleabihf.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@voidzero-dev/vite-plus-linux-arm-musleabihf');
          const bindingPackageVersion =
            require('@voidzero-dev/vite-plus-linux-arm-musleabihf/package.json').version;
          if (
            bindingPackageVersion !== '0.1.24' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./vite-plus.linux-arm-gnueabihf.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@voidzero-dev/vite-plus-linux-arm-gnueabihf');
          const bindingPackageVersion =
            require('@voidzero-dev/vite-plus-linux-arm-gnueabihf/package.json').version;
          if (
            bindingPackageVersion !== '0.1.24' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./vite-plus.linux-loong64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@voidzero-dev/vite-plus-linux-loong64-musl');
          const bindingPackageVersion =
            require('@voidzero-dev/vite-plus-linux-loong64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.1.24' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./vite-plus.linux-loong64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@voidzero-dev/vite-plus-linux-loong64-gnu');
          const bindingPackageVersion =
            require('@voidzero-dev/vite-plus-linux-loong64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.1.24' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./vite-plus.linux-riscv64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@voidzero-dev/vite-plus-linux-riscv64-musl');
          const bindingPackageVersion =
            require('@voidzero-dev/vite-plus-linux-riscv64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.1.24' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./vite-plus.linux-riscv64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@voidzero-dev/vite-plus-linux-riscv64-gnu');
          const bindingPackageVersion =
            require('@voidzero-dev/vite-plus-linux-riscv64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.1.24' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./vite-plus.linux-ppc64-gnu.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-linux-ppc64-gnu');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-linux-ppc64-gnu/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./vite-plus.linux-s390x-gnu.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-linux-s390x-gnu');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-linux-s390x-gnu/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`));
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./vite-plus.openharmony-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-openharmony-arm64');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-openharmony-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./vite-plus.openharmony-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-openharmony-x64');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-openharmony-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./vite-plus.openharmony-arm.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@voidzero-dev/vite-plus-openharmony-arm');
        const bindingPackageVersion =
          require('@voidzero-dev/vite-plus-openharmony-arm/package.json').version;
        if (
          bindingPackageVersion !== '0.1.24' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.1.24 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`));
    }
  } else {
    loadErrors.push(
      new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`),
    );
  }
}

nativeBinding = requireNative();

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null;
  let wasiBindingError = null;
  try {
    wasiBinding = require('./vite-plus.wasi.cjs');
    nativeBinding = wasiBinding;
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err;
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('@voidzero-dev/vite-plus-wasm32-wasi');
      nativeBinding = wasiBinding;
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err;
        } else {
          wasiBindingError.cause = err;
        }
        loadErrors.push(err);
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error');
    error.cause = wasiBindingError;
    throw error;
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err;
          return cur;
        }),
      },
    );
  }
  throw new Error(`Failed to load native binding`);
}

module.exports = nativeBinding;
module.exports.LegalCommentsMode = nativeBinding.LegalCommentsMode;
module.exports.minify = nativeBinding.minify;
module.exports.minifySync = nativeBinding.minifySync;
module.exports.Severity = nativeBinding.Severity;
module.exports.ParseResult = nativeBinding.ParseResult;
module.exports.ExportExportNameKind = nativeBinding.ExportExportNameKind;
module.exports.ExportImportNameKind = nativeBinding.ExportImportNameKind;
module.exports.ExportLocalNameKind = nativeBinding.ExportLocalNameKind;
module.exports.ImportNameKind = nativeBinding.ImportNameKind;
module.exports.parse = nativeBinding.parse;
module.exports.parseSync = nativeBinding.parseSync;
module.exports.rawTransferSupported = nativeBinding.rawTransferSupported;
module.exports.ResolverFactory = nativeBinding.ResolverFactory;
module.exports.EnforceExtension = nativeBinding.EnforceExtension;
module.exports.ModuleType = nativeBinding.ModuleType;
module.exports.sync = nativeBinding.sync;
module.exports.HelperMode = nativeBinding.HelperMode;
module.exports.isolatedDeclaration = nativeBinding.isolatedDeclaration;
module.exports.isolatedDeclarationSync = nativeBinding.isolatedDeclarationSync;
module.exports.moduleRunnerTransform = nativeBinding.moduleRunnerTransform;
module.exports.moduleRunnerTransformSync = nativeBinding.moduleRunnerTransformSync;
module.exports.transform = nativeBinding.transform;
module.exports.transformSync = nativeBinding.transformSync;
module.exports.BindingBundleEndEventData = nativeBinding.BindingBundleEndEventData;
module.exports.BindingBundleErrorEventData = nativeBinding.BindingBundleErrorEventData;
module.exports.BindingBundler = nativeBinding.BindingBundler;
module.exports.BindingCallableBuiltinPlugin = nativeBinding.BindingCallableBuiltinPlugin;
module.exports.BindingChunkingContext = nativeBinding.BindingChunkingContext;
module.exports.BindingDecodedMap = nativeBinding.BindingDecodedMap;
module.exports.BindingDevEngine = nativeBinding.BindingDevEngine;
module.exports.BindingLoadPluginContext = nativeBinding.BindingLoadPluginContext;
module.exports.BindingMagicString = nativeBinding.BindingMagicString;
module.exports.BindingModuleInfo = nativeBinding.BindingModuleInfo;
module.exports.BindingNormalizedOptions = nativeBinding.BindingNormalizedOptions;
module.exports.BindingOutputAsset = nativeBinding.BindingOutputAsset;
module.exports.BindingOutputChunk = nativeBinding.BindingOutputChunk;
module.exports.BindingPluginContext = nativeBinding.BindingPluginContext;
module.exports.BindingRenderedChunk = nativeBinding.BindingRenderedChunk;
module.exports.BindingRenderedChunkMeta = nativeBinding.BindingRenderedChunkMeta;
module.exports.BindingRenderedModule = nativeBinding.BindingRenderedModule;
module.exports.BindingSourceMap = nativeBinding.BindingSourceMap;
module.exports.BindingTransformPluginContext = nativeBinding.BindingTransformPluginContext;
module.exports.BindingWatcher = nativeBinding.BindingWatcher;
module.exports.BindingWatcherBundler = nativeBinding.BindingWatcherBundler;
module.exports.BindingWatcherChangeData = nativeBinding.BindingWatcherChangeData;
module.exports.BindingWatcherEvent = nativeBinding.BindingWatcherEvent;
module.exports.ParallelJsPluginRegistry = nativeBinding.ParallelJsPluginRegistry;
module.exports.ScheduledBuild = nativeBinding.ScheduledBuild;
module.exports.TraceSubscriberGuard = nativeBinding.TraceSubscriberGuard;
module.exports.TsconfigCache = nativeBinding.TsconfigCache;
module.exports.BindingAttachDebugInfo = nativeBinding.BindingAttachDebugInfo;
module.exports.BindingBuiltinPluginName = nativeBinding.BindingBuiltinPluginName;
module.exports.BindingChunkModuleOrderBy = nativeBinding.BindingChunkModuleOrderBy;
module.exports.BindingLogLevel = nativeBinding.BindingLogLevel;
module.exports.BindingPluginOrder = nativeBinding.BindingPluginOrder;
module.exports.BindingPropertyReadSideEffects = nativeBinding.BindingPropertyReadSideEffects;
module.exports.BindingPropertyWriteSideEffects = nativeBinding.BindingPropertyWriteSideEffects;
module.exports.BindingRebuildStrategy = nativeBinding.BindingRebuildStrategy;
module.exports.collapseSourcemaps = nativeBinding.collapseSourcemaps;
module.exports.enhancedTransform = nativeBinding.enhancedTransform;
module.exports.enhancedTransformSync = nativeBinding.enhancedTransformSync;
module.exports.FilterTokenKind = nativeBinding.FilterTokenKind;
module.exports.initTraceSubscriber = nativeBinding.initTraceSubscriber;
module.exports.registerPlugins = nativeBinding.registerPlugins;
module.exports.resolveTsconfig = nativeBinding.resolveTsconfig;
module.exports.shutdownAsyncRuntime = nativeBinding.shutdownAsyncRuntime;
module.exports.startAsyncRuntime = nativeBinding.startAsyncRuntime;
module.exports.detectWorkspace = nativeBinding.detectWorkspace;
module.exports.downloadPackageManager = nativeBinding.downloadPackageManager;
module.exports.hasConfigKey = nativeBinding.hasConfigKey;
module.exports.mergeJsonConfig = nativeBinding.mergeJsonConfig;
module.exports.mergeTsdownConfig = nativeBinding.mergeTsdownConfig;
module.exports.rewriteEslint = nativeBinding.rewriteEslint;
module.exports.rewriteImportsInDirectory = nativeBinding.rewriteImportsInDirectory;
module.exports.rewritePrettier = nativeBinding.rewritePrettier;
module.exports.rewriteScripts = nativeBinding.rewriteScripts;
module.exports.run = nativeBinding.run;
module.exports.runCommand = nativeBinding.runCommand;
module.exports.shouldPrintVitePlusHeader = nativeBinding.shouldPrintVitePlusHeader;
module.exports.vitePlusHeader = nativeBinding.vitePlusHeader;
module.exports.wrapLazyPlugins = nativeBinding.wrapLazyPlugins;
