[package]
name = "vp_global_cli"
version = "0.2.8"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[[bin]]
name = "vp"
path = "src/main.rs"

[dependencies]
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
clap_complete = { workspace = true, features = ["unstable-dynamic"] }
directories = { workspace = true }
dialoguer = { workspace = true }
futures = { workspace = true }
flate2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
node-semver = { workspace = true }
thiserror = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
owo-colors = { workspace = true }
oxc_resolver = { workspace = true }
crossterm = { workspace = true }
indexmap = { workspace = true }
indicatif = { workspace = true }
vp_error = { workspace = true }
vp_js_runtime = { workspace = true }
vp_pm_cli = { workspace = true }
vt_path = { workspace = true }
vp_command = { workspace = true }
vp_setup = { workspace = true }
vp_shared = { workspace = true }
vt_str = { workspace = true }
vt_workspace = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
serial_test = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
