// This file is auto-generated by `cargo test`. Do not edit manually.

export type AutoTracking = {
/**
 * Enable automatic file tracking for this input or output list.
 */
auto: boolean, };

export type Command = string | Array<string>;

export type DependencyType = "dependencies" | "devDependencies" | "peerDependencies";

export type DependsOnEntry = string | UserPackageDependency;

export type DependsOnFrom = DependencyType | Array<DependencyType>;

export type GlobWithBase = {
/**
 * The glob pattern (positive or negative starting with `!`)
 */
pattern: string,
/**
 * The base directory for resolving the pattern
 */
base: InputBase, };

export type InputBase = "package" | "workspace";

export type Task = {
/**
 * Command to run, or an array of commands to run in order.
 */
command: Command,
/**
 * The working directory for the task, relative to the package root (not workspace root).
 */
cwd?: string,
/**
 * Tasks that must run before this task.
 *
 * - A string runs one named task, such as `"build"` in the same package or
 *   `"package-name#build"` in another package.
 * - An object runs a task in direct workspace dependency packages selected
 *   from package.json fields. For example,
 *   `{ "task": "build", "from": "dependencies" }` runs `build` in each
 *   direct workspace dependency that defines a `build` task.
 */
dependsOn?: Array<DependsOnEntry>, } & ({
/**
 * Whether to cache the task
 */
cache?: true,
/**
 * Environment variable names to be fingerprinted and passed to the task.
 */
env?: Array<string>,
/**
 * Environment variable names to be passed to the task without fingerprinting.
 */
untrackedEnv?: Array<string>,
/**
 * Files to include in the cache fingerprint.
 *
 * - Omitted: automatically tracks which files the task reads
 * - `[]` (empty): disables file tracking entirely
 * - Glob patterns (e.g. `"src/**"`) select specific files, relative to the package directory
 * - `{pattern: "...", base: "workspace" | "package"}` specifies a glob with an explicit base directory
 * - `{auto: true}` enables automatic file tracking
 * - Negative patterns (e.g. `"!dist/**"`) exclude matched files
 */
input?: Array<string | GlobWithBase | AutoTracking>,
/**
 * Output files to archive and restore on cache hit.
 *
 * - Omitted: automatically tracks which files the task writes
 * - `[]` (empty): disables output restoration entirely
 * - Glob patterns (e.g. `"dist/**"`) select specific output files, relative to the package directory
 * - `{pattern: "...", base: "workspace" | "package"}` specifies a glob with an explicit base directory
 * - `{auto: true}` enables automatic output tracking
 * - Negative patterns (e.g. `"!dist/cache/**"`) exclude matched files
 */
output?: Array<string | GlobWithBase | AutoTracking>, } | {
/**
 * Whether to cache the task
 */
cache: false, });

export type TaskDefinition = Task | Command;

export type UserGlobalCacheConfig = boolean | {
/**
 * Enable caching for package.json scripts not defined in the `tasks` map.
 *
 * When `false`, package.json scripts will not be cached.
 * When `true`, package.json scripts will be cached with default settings.
 *
 * Default: `false`
 */
scripts?: boolean,
/**
 * Global cache kill switch for task entries.
 *
 * When `false`, overrides all tasks to disable caching, even tasks with `cache: true`.
 * When `true`, respects each task's individual `cache` setting
 * (each task's `cache` defaults to `true` if omitted).
 *
 * Default: `true`
 */
tasks?: boolean, };

export type UserPackageDependency = {
/**
 * Task name to run in dependency packages.
 */
task: string,
/**
 * Package.json dependency field or fields to use when selecting direct dependency packages.
 */
from: DependsOnFrom, };

export type RunConfig = {
/**
 * Root-level cache configuration.
 *
 * This option can only be set in the workspace root's config file.
 * Setting it in a package's config will result in an error.
 */
cache?: UserGlobalCacheConfig,
/**
 * Task definitions: full task objects, command strings, or command string arrays.
 */
tasks?: { [key in string]: TaskDefinition },
/**
 * Whether to automatically run `preX`/`postX` package.json scripts as
 * lifecycle hooks when script `X` is executed.
 *
 * When `true` (the default), running script `test` will automatically
 * run `pretest` before and `posttest` after, if they exist.
 *
 * This option can only be set in the workspace root's config file.
 * Setting it in a package's config will result in an error.
 */
enablePrePostScripts?: boolean, };
