import fs from 'node:fs';
import path from 'node:path';

import cliPkg from '../package.json' with { type: 'json' };
import { VITE_PLUS_NAME } from './utils/constants.ts';
import { renderCliDoc } from './utils/help.ts';
import { detectPackageMetadata, hasVitePlusDependency } from './utils/package.ts';
import { accent, log, printHeader } from './utils/terminal.ts';

/** Tool display names in the order shown by `vp --version`. */
const TOOL_DISPLAY_ORDER = [
  'vite',
  'rolldown',
  'vitest',
  'oxfmt',
  'oxlint',
  'oxlint-tsgolint',
  'tsdown',
] as const;

interface LocalPackageMetadata {
  name: string;
  version: string;
  path: string;
}

function getGlobalVersion(): string | null {
  return process.env.VP_GLOBAL_VERSION ?? null;
}

function getCliVersion(): string | null {
  return cliPkg.version ?? null;
}

function getLocalMetadata(cwd: string): LocalPackageMetadata | null {
  if (!isVitePlusDeclaredInAncestors(cwd)) {
    return null;
  }
  return detectPackageMetadata(cwd, VITE_PLUS_NAME) ?? null;
}

function isVitePlusDeclaredInAncestors(cwd: string): boolean {
  let currentDir = path.resolve(cwd);
  while (true) {
    const packageJsonPath = path.join(currentDir, 'package.json');
    try {
      const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
      if (hasVitePlusDependency(pkg)) {
        return true;
      }
    } catch {
      // no package.json at this level
    }
    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) {
      break;
    }
    currentDir = parentDir;
  }
  return false;
}

/**
 * Resolve all tool versions from the locally installed vite-plus package.
 * Uses the `vite-plus/versions` export generated by `syncVersionsExport()`.
 */
async function resolveToolVersions(localPackagePath: string): Promise<Record<string, string>> {
  try {
    const mod = await import(`${localPackagePath}/dist/versions.js`);
    if (mod.versions && typeof mod.versions === 'object') {
      return mod.versions as Record<string, string>;
    }
  } catch {
    // versions module not available
  }
  return {};
}

/**
 * Print version information
 */
export async function printVersion(cwd: string) {
  const globalVersion = getGlobalVersion();
  const cliVersion = getCliVersion();
  const localMetadata = getLocalMetadata(cwd);
  const localVersion = localMetadata?.version ?? null;
  const vpVersion = globalVersion ?? cliVersion ?? localVersion ?? 'unknown';

  printHeader();
  log(`vp v${vpVersion}\n`);

  const sections = [
    {
      title: 'Local vite-plus',
      rows: [
        {
          label: accent('vite-plus'),
          description: localVersion ? `v${localVersion}` : 'Not found',
        },
      ],
    },
  ];

  if (localMetadata) {
    const versions = await resolveToolVersions(localMetadata.path);

    sections.push({
      title: 'Tools',
      rows: TOOL_DISPLAY_ORDER.map((name) => ({
        label: accent(name),
        description: versions[name] ? `v${versions[name]}` : 'Not found',
      })),
    });
  }

  log(renderCliDoc({ sections }));
}

await printVersion(process.cwd());
