packages:
  - .

catalogs:
  repo-tooling:
    prettier: 3.8.3
  vite-stack:
    vite: npm:@voidzero-dev/vite-plus-core@0.1.21
    vitest: npm:@voidzero-dev/vite-plus-test@0.1.21
    vite-plus: 0.1.21
