//! Typed package-manager command resolution.
//!
//! The production-facing seam is [`resolve_for_manager`]. It accepts the
//! detected [`crate::PackageManager`] and one typed clap argument value.
//! The resolver then:
//!
//! 1. runs the diagnosis generated by `#[pm_args]` and removes unsupported arguments;
//! 2. lowers the remaining arguments for the selected package manager;
//! 3. binds the detected package manager's managed binary directory to `PATH`;
//! 4. returns both the [`CommandResolution`] and any [`Diagnostics`].
//!
//! Resolution only builds a command. It never performs pre-run actions or
//! spawns a process. Pass the complete result to [`run_resolution`] to render
//! diagnostics and execute it from the caller's working directory.
//!
//! # Caller flow
//!
//! ```ignore
//! let resolution = resolve_for_manager(&package_manager, args)?;
//! run_resolution(cwd, resolution, true).await
//! ```
//!
//! [`run_resolution`] can render diagnostics before handling the outcome.
//! Callers disable rendering for explicit silent modes. Machine-readable output
//! remains on stdout while diagnostics use stderr. A no-op returns success, an
//! invalid argument becomes a user-facing error, and a run executes every
//! pre-run action before spawning the resolved command. Keeping those side
//! effects outside resolution lets tests inspect the complete plan.

mod command;
mod commands;
mod diagnostics;
mod dialect;
mod resolve;
mod runner;
mod support;
#[cfg(test)]
pub(crate) mod test_utils;

use command::CommandBuilder;
/// Control-flow outcome produced by [`resolve_for_manager`].
pub(crate) use command::CommandResolution;
pub(crate) use commands::SaveDependencyArgs;
/// Typed clap argument values accepted by [`resolve_for_manager`].
#[expect(unused_imports, reason = "typed command arguments form the production CLI surface")]
pub use commands::{
    AddArgs, ApproveBuildsArgs, AuditArgs, CacheArgs, CiArgs, ConfigCommand, DedupeArgs,
    DeprecateArgs, DistTagCommand, DlxArgs, FundArgs, InstallArgs, LinkArgs, ListArgs, LoginArgs,
    LogoutArgs, OutdatedArgs, OutdatedFormat, OwnerCommand, PackArgs, PatchArgs, PatchCommitArgs,
    PingArgs, PruneArgs, PublishArgs, RebuildArgs, RemoveArgs, SearchArgs, StageCommand,
    TokenCommand, UnlinkArgs, UpdateArgs, VersionArgs, ViewArgs, WhoamiArgs, WhyArgs,
};
use diagnostics::DiagnosticKind;
/// Diagnostics emitted while unsupported arguments and fallbacks are resolved.
pub(crate) use diagnostics::Diagnostics;
use dialect::{Bun, Npm, PackageManagerDialect, Pnpm, Yarn};
/// Complete translation result returned to production dispatch.
pub(crate) use resolve::Resolution;
use resolve::Resolve;
#[cfg(test)]
pub(crate) use resolve::resolve;
/// Resolves typed arguments for a detected package manager without executing them.
///
/// This is the only resolver entry point production dispatch should call.
pub(crate) use resolve::resolve_for_manager;
/// Renders and executes a complete package-manager command resolution.
pub(crate) use runner::run_resolution;
use support::{ArgActivation, Diagnosis, PmSupportRule, VersionOperator};
