name: Release

on:
  workflow_dispatch:

permissions: {}

jobs:
  build-rust:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          # - x86_64-pc-windows-msvc
          # - aarch64-pc-windows-msvc
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: oxc-project/setup-rust@d286d43bc1f606abbd98096666ff8be68c8d5f57 # v1.0.2
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: release

      - uses: mlugg/setup-zig@8d6198c65fb0feaa111df26e6b467fea8345e46f # v2.0.5
        with:
          version: 0.15.1

      - uses: taiki-e/install-action@ad95d4e02e061d4390c4b66ef5ed56c7fee3d2ce # v2.58.17
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tool: cargo-zigbuild

      - uses: taiki-e/install-action@ad95d4e02e061d4390c4b66ef5ed56c7fee3d2ce # v2.58.17
        if: ${{ contains(matrix.target, 'windows') }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tool: cargo-xwin

      - name: Install llvm
        if: ${{ contains(matrix.target, 'windows') }}
        run: brew install llvm

      - name: Rustup Adds Target
        run: rustup target add ${{ matrix.target }}

      - name: Add musl target (x86_64)
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
        run: rustup target add x86_64-unknown-linux-musl

      - name: Add musl target (aarch64)
        if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
        run: rustup target add aarch64-unknown-linux-musl

      - uses: oxc-project/setup-node@376ec3eb2d5cad9c200e276b7e760cad6b646d05 # main

      - name: Build
        run: pnpm --filter=@voidzero-dev/vite-plus build --target ${{ matrix.target }} -x
        env:
          XWIN_CACHE_DIR: ${{ github.workspace }}/.xwin-cache

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: bindings-${{ matrix.target }}
          path: ./packages/cli/binding/*.node
          if-no-files-found: error

  Release:
    runs-on: ubuntu-latest
    needs: build-rust
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: oxc-project/setup-node@376ec3eb2d5cad9c200e276b7e760cad6b646d05 # main

      - name: Bootstrap
        run: pnpm bootstrap-cli:ci

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: packages/global/dist
          pattern: bindings-*
          merge-multiple: true

      - name: Build
        run: vite run @voidzero-dev/vite-plus#build @voidzero-dev/global#build

      # Download again because `@voidzero-dev/global#build` will cleanup the dist dir first
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: packages/global/dist
          pattern: bindings-*
          merge-multiple: true

      - name: Copy *.node to cli/dist
        run: |
          cp -r packages/global/dist/*.node packages/cli/dist
          ls -alh packages/cli/dist

      - name: Set version
        run: |
          sed -i 's/"version": "0.0.0"/"version": "0.0.0-${{ github.sha }}"/' packages/global/package.json
          sed -i 's/"version": "0.0.0"/"version": "0.0.0-${{ github.sha }}"/' packages/cli/package.json

      # Setup node correctly for publishing to github registry
      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          registry-url: "https://npm.pkg.github.com"
          scope: "@voidzero-dev"
          package-manager-cache: false

      - run: npm install -g npm@latest # For trusted publishing support

      - name: Publish
        run: |
          pnpm publish --filter=./packages/global --registry https://npm.pkg.github.com --no-git-checks
          pnpm publish --filter=./packages/cli --registry https://npm.pkg.github.com --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
